export const LOGIN = '@@AUTH/LOGIN'
export const SET_CURRENT_API_TOKEN = '@@AUTH/SET_CURRENT_API_TOKEN'
export const UNSET_CURRENT_API_TOKEN = '@@AUTH/UNSET_CURRENT_API_TOKEN'
export const SET_LOGIN_ERROR = '@@AUTH/SET_LOGIN_ERROR'