export const SEARCH_ARTICLES = 'ARTICLES/SEARCH_ARTICLES'
export const SEARCH_ARTICLES_SUCCESS = 'ARTICLES/SEARCH_ARTICLES_SUCCESS'
export const SEARCH_ARTICLES_ERROR = 'ARTICLES/SEARCH_ARTICLES_ERROR'